version: '3.7'

services:
  web:
    image: python:3.9.6-alpine
    container_name: django
    build:
      dockerfile: Dockerfile.web
      context: .
    working_dir: "/usr/src/web"
    volumes:
      - ./web/:/usr/src/web/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  db:
    image: postgres:12.0-alpine
    container_name: db_postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "${DB_PORT:-5432}:5432"
  bot:
    image: python:3.10-buster
    container_name: bot
    build:
      dockerfile: Dockerfile.bot
      context: .
    working_dir: "/usr/src/bot"
    volumes:
      - ./bot/:/usr/src/bot/
    command: python main.py dev
    depends_on:
      - web


