FROM python:3.10-buster

WORKDIR /usr/src/bot

COPY requirements.txt /usr/src/bot

RUN python -m pip install --upgrade pip; \
    pip install -r /usr/src/bot/requirements.txt

COPY . /usr/src/bot

CMD python main.py $MODE