version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: db_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  web:
    build: web
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  bot:
    build: bot
    container_name: bot
    volumes:
      - ./bot/:/usr/src/bot/
    command: python main.py
    depends_on:
      - web


